input {
  http {
    host  => "0.0.0.0"
    port  => 5044
    codec => json {
      ecs_compatibility => "disabled"
    }
  }
}

filter { ruby { code => "event.set('timestamp', event.get('@timestamp'))" } }

output {
  if [name] == "dht" {
    opensearch {
      hosts => ["https://opensearch:9200"]
      index => "weather-%{+YYYY.MM.dd}"
      user => "${OPENSEARCH_USER}"
      password => "${OPENSEARCH_PASSWORD}"
      ssl_certificate_verification => false
    }
  } else if [name] == "hygrometer" {
    opensearch {
      hosts => ["https://opensearch:9200"]
      index => "sensor-%{+YYYY.MM.dd}"
      user => "${OPENSEARCH_USER}"
      password => "${OPENSEARCH_PASSWORD}"
      ssl_certificate_verification => false
    }
  } else {
    opensearch {
      hosts => ["https://opensearch:9200"]
      index => "unclassified-%{+YYYY.MM.dd}"
      user => "${OPENSEARCH_USER}"
      password => "${OPENSEARCH_PASSWORD}"
      ssl_certificate_verification => false
    }
  }
}